# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read #  to fetch code (actions/checkout)

env:
  # run static analysis only with the latest Go version
  LATEST_GO_VERSION: "1.22"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.LATEST_GO_VERSION }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Run golint
      run: |
        go install golang.org/x/lint/golint@latest
        golint -set_exit_status ./...

    - name: Run staticcheck
      run: |
        go install honnef.co/go/tools/cmd/staticcheck@latest
        staticcheck ./...

    - name: Run govulncheck
      run: |
        go version
        go install golang.org/x/vuln/cmd/govulncheck@latest
        govulncheck ./...
